var story = {
 "docName": "Finpay - UI Kit (Community)",
 "docPath": "P_P_P",
 "docVersion": "V_V_V",
 "ownerName": "Maxim Bazarov",
 "ownerEmail": "max@bazarov.ru",
 "authorName": "V_V_N",
 "authorEmail": "V_V_E",
 "commentsURL": "V_V_C",
 "hasRetina": true,
 "serverToolsPath": "",
 "fontSizeFormat": -1,
 "fileType": "png",
 "disableInteractions": false,
 "disableHotspots": false,
 "zoomEnabled": true,
 "title": "Demo",
 "layersExist": true,
 "highlightLinks": true,
 "pages": [
  {
   "id": "47:2205",
   "groupID": "0:1",
   "transAnimType": 0,
   "title": "Label",
   "image": "label.png",
   "image2x": "label@2x.png",
   "index": 0,
   "width": 1440,
   "height": 164,
   "x": -1637,
   "y": 101,
   "type": "regular",
   "fixedPanels": [],
   "links": [],
   "overlayPinPage": 6,
   "overlayOutsideClickIgnore": true,
   "layout": null
  },
  {
   "id": "31:2338",
   "groupID": "0:1",
   "transAnimType": 0,
   "title": "1. Splash Screen",
   "image": "1.-splash-screen.png",
   "image2x": "1.-splash-screen@2x.png",
   "index": 1,
   "width": 375,
   "height": 812,
   "x": -1629,
   "y": 465,
   "type": "regular",
   "fixedPanels": [],
   "links": [],
   "overlayPinPage": 6,
   "overlayOutsideClickIgnore": true,
   "layout": null
  },
  {
   "id": "31:3319",
   "groupID": "0:1",
   "transAnimType": 0,
   "title": "11. Sign up - Empty",
   "image": "11.-sign-up-empty.png",
   "image2x": "11.-sign-up-empty@2x.png",
   "index": 2,
   "width": 375,
   "height": 812,
   "x": -1629,
   "y": 1417,
   "type": "regular",
   "fixedPanels": [],
   "links": [],
   "overlayPinPage": 6,
   "overlayOutsideClickIgnore": true,
   "layout": null
  },
  {
   "id": "52:2969",
   "groupID": "0:1",
   "transAnimType": 0,
   "title": "21. Home",
   "image": "21.-home.png",
   "image2x": "21.-home@2x.png",
   "index": 3,
   "width": 375,
   "height": 812,
   "x": -1629,
   "y": 2369,
   "type": "regular",
   "fixedPanels": [],
   "links": [],
   "overlayPinPage": 6,
   "overlayOutsideClickIgnore": true,
   "layout": null
  },
  {
   "id": "111:3834",
   "groupID": "0:1",
   "transAnimType": 0,
   "title": "31. Statistic - V1",
   "image": "31.-statistic-v1.png",
   "image2x": "31.-statistic-v1@2x.png",
   "index": 4,
   "width": 375,
   "height": 812,
   "x": -1629,
   "y": 3321,
   "type": "regular",
   "fixedPanels": [],
   "links": [],
   "overlayPinPage": 6,
   "overlayOutsideClickIgnore": true,
   "layout": null
  },
  {
   "id": "115:4956",
   "groupID": "0:1",
   "transAnimType": 0,
   "title": "2. Onboarding - 1",
   "image": "2.-onboarding-1.png",
   "image2x": "2.-onboarding-1@2x.png",
   "index": 5,
   "width": 375,
   "height": 812,
   "x": -1214,
   "y": 465,
   "type": "regular",
   "fixedPanels": [],
   "links": [],
   "overlayPinPage": 6,
   "overlayOutsideClickIgnore": true,
   "layout": null
  },
  {
   "id": "31:3450",
   "groupID": "0:1",
   "transAnimType": 0,
   "title": "12. Sign up - Filled",
   "image": "12.-sign-up-filled.png",
   "image2x": "12.-sign-up-filled@2x.png",
   "index": 6,
   "width": 375,
   "height": 812,
   "x": -1214,
   "y": 1417,
   "type": "regular",
   "fixedPanels": [],
   "links": [],
   "overlayPinPage": 6,
   "overlayOutsideClickIgnore": true,
   "layout": null
  },
  {
   "id": "52:3204",
   "groupID": "0:1",
   "transAnimType": 0,
   "title": "22. Topup",
   "image": "22.-topup.png",
   "image2x": "22.-topup@2x.png",
   "index": 7,
   "width": 375,
   "height": 812,
   "x": -1214,
   "y": 2369,
   "type": "regular",
   "fixedPanels": [],
   "links": [],
   "overlayPinPage": 6,
   "overlayOutsideClickIgnore": true,
   "layout": null
  },
  {
   "id": "112:4011",
   "groupID": "0:1",
   "transAnimType": 0,
   "title": "32. Statistic - V2",
   "image": "32.-statistic-v2.png",
   "image2x": "32.-statistic-v2@2x.png",
   "index": 8,
   "width": 375,
   "height": 812,
   "x": -1214,
   "y": 3321,
   "type": "regular",
   "fixedPanels": [],
   "links": [],
   "overlayPinPage": 6,
   "overlayOutsideClickIgnore": true,
   "layout": null
  },
  {
   "id": "115:4922",
   "groupID": "0:1",
   "transAnimType": 0,
   "title": "3. Onboarding - 2",
   "image": "3.-onboarding-2.png",
   "image2x": "3.-onboarding-2@2x.png",
   "index": 9,
   "width": 375,
   "height": 812,
   "x": -799,
   "y": 465,
   "type": "regular",
   "fixedPanels": [],
   "links": [],
   "overlayPinPage": 6,
   "overlayOutsideClickIgnore": true,
   "layout": null
  },
  {
   "id": "7:4837",
   "groupID": "0:1",
   "transAnimType": 0,
   "title": "13. Country of Residence",
   "image": "13.-country-of-residence.png",
   "image2x": "13.-country-of-residence@2x.png",
   "index": 10,
   "width": 375,
   "height": 812,
   "x": -799,
   "y": 1417,
   "type": "regular",
   "fixedPanels": [],
   "links": [],
   "overlayPinPage": 6,
   "overlayOutsideClickIgnore": true,
   "layout": null
  },
  {
   "id": "63:5086",
   "groupID": "0:1",
   "transAnimType": 0,
   "title": "23. Topup - Confirmation",
   "image": "23.-topup-confirmation.png",
   "image2x": "23.-topup-confirmation@2x.png",
   "index": 11,
   "width": 375,
   "height": 812,
   "x": -799,
   "y": 2369,
   "type": "regular",
   "fixedPanels": [],
   "links": [],
   "overlayPinPage": 6,
   "overlayOutsideClickIgnore": true,
   "layout": null
  },
  {
   "id": "103:3911",
   "groupID": "0:1",
   "transAnimType": 0,
   "title": "33. My Card",
   "image": "33.-my-card.png",
   "image2x": "33.-my-card@2x.png",
   "index": 12,
   "width": 375,
   "height": 812,
   "x": -799,
   "y": 3321,
   "type": "regular",
   "fixedPanels": [],
   "links": [],
   "overlayPinPage": 6,
   "overlayOutsideClickIgnore": true,
   "layout": null
  },
  {
   "id": "31:2093",
   "groupID": "0:1",
   "transAnimType": 0,
   "title": "4. Login - Empty",
   "image": "4.-login-empty.png",
   "image2x": "4.-login-empty@2x.png",
   "index": 13,
   "width": 375,
   "height": 812,
   "x": -384,
   "y": 465,
   "type": "regular",
   "fixedPanels": [],
   "links": [],
   "overlayPinPage": 6,
   "overlayOutsideClickIgnore": true,
   "layout": null
  },
  {
   "id": "99:3875",
   "groupID": "0:1",
   "transAnimType": 0,
   "title": "14. Country of Residence - Select",
   "image": "14.-country-of-residence-select.png",
   "image2x": "14.-country-of-residence-select@2x.png",
   "index": 14,
   "width": 375,
   "height": 812,
   "x": -384,
   "y": 1417,
   "type": "regular",
   "fixedPanels": [],
   "links": [],
   "overlayPinPage": 6,
   "overlayOutsideClickIgnore": true,
   "layout": null
  },
  {
   "id": "52:3370",
   "groupID": "0:1",
   "transAnimType": 0,
   "title": "24. Success - Topup",
   "image": "24.-success-topup.png",
   "image2x": "24.-success-topup@2x.png",
   "index": 15,
   "width": 375,
   "height": 812,
   "x": -384,
   "y": 2369,
   "type": "regular",
   "fixedPanels": [],
   "links": [],
   "overlayPinPage": 6,
   "overlayOutsideClickIgnore": true,
   "layout": null
  },
  {
   "id": "103:3990",
   "groupID": "0:1",
   "transAnimType": 0,
   "title": "34. My Card - Add New Card",
   "image": "34.-my-card-add-new-card.png",
   "image2x": "34.-my-card-add-new-card@2x.png",
   "index": 16,
   "width": 375,
   "height": 812,
   "x": -384,
   "y": 3321,
   "type": "regular",
   "fixedPanels": [],
   "links": [],
   "overlayPinPage": 6,
   "overlayOutsideClickIgnore": true,
   "layout": null
  },
  {
   "id": "31:2146",
   "groupID": "0:1",
   "transAnimType": 0,
   "title": "5. Login - Filled",
   "image": "5.-login-filled.png",
   "image2x": "5.-login-filled@2x.png",
   "index": 17,
   "width": 375,
   "height": 812,
   "x": 31,
   "y": 465,
   "type": "regular",
   "fixedPanels": [],
   "links": [],
   "overlayPinPage": 6,
   "overlayOutsideClickIgnore": true,
   "layout": null
  },
  {
   "id": "7:4839",
   "groupID": "0:1",
   "transAnimType": 0,
   "title": "15. Select Reason ",
   "image": "15.-select-reason-.png",
   "image2x": "15.-select-reason-@2x.png",
   "index": 18,
   "width": 375,
   "height": 812,
   "x": 31,
   "y": 1417,
   "type": "regular",
   "fixedPanels": [],
   "links": [],
   "overlayPinPage": 6,
   "overlayOutsideClickIgnore": true,
   "layout": null
  },
  {
   "id": "12:17707",
   "groupID": "0:1",
   "transAnimType": 0,
   "title": "25. Transfer",
   "image": "25.-transfer.png",
   "image2x": "25.-transfer@2x.png",
   "index": 19,
   "width": 375,
   "height": 812,
   "x": 31,
   "y": 2369,
   "type": "regular",
   "fixedPanels": [],
   "links": [],
   "overlayPinPage": 6,
   "overlayOutsideClickIgnore": true,
   "layout": null
  },
  {
   "id": "103:4021",
   "groupID": "0:1",
   "transAnimType": 0,
   "title": "35. My Card - Create Pin",
   "image": "35.-my-card-create-pin.png",
   "image2x": "35.-my-card-create-pin@2x.png",
   "index": 20,
   "width": 375,
   "height": 812,
   "x": 31,
   "y": 3321,
   "type": "regular",
   "fixedPanels": [],
   "links": [],
   "overlayPinPage": 6,
   "overlayOutsideClickIgnore": true,
   "layout": null
  },
  {
   "id": "31:2206",
   "groupID": "0:1",
   "transAnimType": 0,
   "title": "6. OTP Authentication",
   "image": "6.-otp-authentication.png",
   "image2x": "6.-otp-authentication@2x.png",
   "index": 21,
   "width": 375,
   "height": 812,
   "x": 446,
   "y": 465,
   "type": "regular",
   "fixedPanels": [],
   "links": [],
   "overlayPinPage": 6,
   "overlayOutsideClickIgnore": true,
   "layout": null
  },
  {
   "id": "7:4840",
   "groupID": "0:1",
   "transAnimType": 0,
   "title": "16. Create Pin",
   "image": "16.-create-pin.png",
   "image2x": "16.-create-pin@2x.png",
   "index": 22,
   "width": 375,
   "height": 812,
   "x": 446,
   "y": 1417,
   "type": "regular",
   "fixedPanels": [],
   "links": [],
   "overlayPinPage": 6,
   "overlayOutsideClickIgnore": true,
   "layout": null
  },
  {
   "id": "12:17708",
   "groupID": "0:1",
   "transAnimType": 0,
   "title": "26. Transfer - Detail",
   "image": "26.-transfer-detail.png",
   "image2x": "26.-transfer-detail@2x.png",
   "index": 23,
   "width": 375,
   "height": 812,
   "x": 446,
   "y": 2369,
   "type": "regular",
   "fixedPanels": [],
   "links": [],
   "overlayPinPage": 6,
   "overlayOutsideClickIgnore": true,
   "layout": null
  },
  {
   "id": "134:4371",
   "groupID": "0:1",
   "transAnimType": 0,
   "title": "36. Profile",
   "image": "36.-profile.png",
   "image2x": "36.-profile@2x.png",
   "index": 24,
   "width": 375,
   "height": 812,
   "x": 446,
   "y": 3321,
   "type": "regular",
   "fixedPanels": [],
   "links": [],
   "overlayPinPage": 6,
   "overlayOutsideClickIgnore": true,
   "layout": null
  },
  {
   "id": "31:2218",
   "groupID": "0:1",
   "transAnimType": 0,
   "title": "7. Fingerprint",
   "image": "7.-fingerprint.png",
   "image2x": "7.-fingerprint@2x.png",
   "index": 25,
   "width": 375,
   "height": 812,
   "x": 861,
   "y": 465,
   "type": "regular",
   "fixedPanels": [],
   "links": [],
   "overlayPinPage": 6,
   "overlayOutsideClickIgnore": true,
   "layout": null
  },
  {
   "id": "7:4841",
   "groupID": "0:1",
   "transAnimType": 0,
   "title": "17. Verify Identity",
   "image": "17.-verify-identity.png",
   "image2x": "17.-verify-identity@2x.png",
   "index": 26,
   "width": 375,
   "height": 812,
   "x": 861,
   "y": 1417,
   "type": "regular",
   "fixedPanels": [],
   "links": [],
   "overlayPinPage": 6,
   "overlayOutsideClickIgnore": true,
   "layout": null
  },
  {
   "id": "81:2801",
   "groupID": "0:1",
   "transAnimType": 0,
   "title": "27. Transfer - Confirm",
   "image": "27.-transfer-confirm.png",
   "image2x": "27.-transfer-confirm@2x.png",
   "index": 27,
   "width": 375,
   "height": 812,
   "x": 861,
   "y": 2369,
   "type": "regular",
   "fixedPanels": [],
   "links": [],
   "overlayPinPage": 6,
   "overlayOutsideClickIgnore": true,
   "layout": null
  },
  {
   "id": "95:3217",
   "groupID": "0:1",
   "transAnimType": 0,
   "title": "37. My Account",
   "image": "37.-my-account.png",
   "image2x": "37.-my-account@2x.png",
   "index": 28,
   "width": 375,
   "height": 812,
   "x": 861,
   "y": 3321,
   "type": "regular",
   "fixedPanels": [],
   "links": [],
   "overlayPinPage": 6,
   "overlayOutsideClickIgnore": true,
   "layout": null
  },
  {
   "id": "31:2240",
   "groupID": "0:1",
   "transAnimType": 0,
   "title": "8. Password Recovery",
   "image": "8.-password-recovery.png",
   "image2x": "8.-password-recovery@2x.png",
   "index": 29,
   "width": 375,
   "height": 812,
   "x": 1276,
   "y": 465,
   "type": "regular",
   "fixedPanels": [],
   "links": [],
   "overlayPinPage": 6,
   "overlayOutsideClickIgnore": true,
   "layout": null
  },
  {
   "id": "52:3529",
   "groupID": "0:1",
   "transAnimType": 0,
   "title": "18. Proof of residency ",
   "image": "18.-proof-of-residency-.png",
   "image2x": "18.-proof-of-residency-@2x.png",
   "index": 30,
   "width": 375,
   "height": 812,
   "x": 1276,
   "y": 1417,
   "type": "regular",
   "fixedPanels": [],
   "links": [],
   "overlayPinPage": 6,
   "overlayOutsideClickIgnore": true,
   "layout": null
  },
  {
   "id": "81:2870",
   "groupID": "0:1",
   "transAnimType": 0,
   "title": "28. Transfer - Proof",
   "image": "28.-transfer-proof.png",
   "image2x": "28.-transfer-proof@2x.png",
   "index": 31,
   "width": 375,
   "height": 812,
   "x": 1276,
   "y": 2369,
   "type": "regular",
   "fixedPanels": [],
   "links": [],
   "overlayPinPage": 6,
   "overlayOutsideClickIgnore": true,
   "layout": null
  },
  {
   "id": "95:3259",
   "groupID": "0:1",
   "transAnimType": 0,
   "title": "38. Settings",
   "image": "38.-settings.png",
   "image2x": "38.-settings@2x.png",
   "index": 32,
   "width": 375,
   "height": 812,
   "x": 1276,
   "y": 3321,
   "type": "regular",
   "fixedPanels": [],
   "links": [],
   "overlayPinPage": 6,
   "overlayOutsideClickIgnore": true,
   "layout": null
  },
  {
   "id": "31:2262",
   "groupID": "0:1",
   "transAnimType": 0,
   "title": "9. Verify your identity",
   "image": "9.-verify-your-identity.png",
   "image2x": "9.-verify-your-identity@2x.png",
   "index": 33,
   "width": 375,
   "height": 812,
   "x": 1691,
   "y": 465,
   "type": "regular",
   "fixedPanels": [],
   "links": [],
   "overlayPinPage": 6,
   "overlayOutsideClickIgnore": true,
   "layout": null
  },
  {
   "id": "59:2780",
   "groupID": "0:1",
   "transAnimType": 0,
   "title": "19. Upload - Photo ID Card",
   "image": "19.-upload-photo-id-card.png",
   "image2x": "19.-upload-photo-id-card@2x.png",
   "index": 34,
   "width": 375,
   "height": 812,
   "x": 1691,
   "y": 1417,
   "type": "regular",
   "fixedPanels": [],
   "links": [],
   "overlayPinPage": 6,
   "overlayOutsideClickIgnore": true,
   "layout": null
  },
  {
   "id": "81:2960",
   "groupID": "0:1",
   "transAnimType": 0,
   "title": "29. History Trasaction",
   "image": "29.-history-trasaction.png",
   "image2x": "29.-history-trasaction@2x.png",
   "index": 35,
   "width": 375,
   "height": 812,
   "x": 1691,
   "y": 2369,
   "type": "regular",
   "fixedPanels": [],
   "links": [],
   "overlayPinPage": 6,
   "overlayOutsideClickIgnore": true,
   "layout": null
  },
  {
   "id": "95:3377",
   "groupID": "0:1",
   "transAnimType": 0,
   "title": "39. Notification",
   "image": "39.-notification.png",
   "image2x": "39.-notification@2x.png",
   "index": 36,
   "width": 375,
   "height": 812,
   "x": 1691,
   "y": 3321,
   "type": "regular",
   "fixedPanels": [],
   "links": [],
   "overlayPinPage": 6,
   "overlayOutsideClickIgnore": true,
   "layout": null
  },
  {
   "id": "31:2274",
   "groupID": "0:1",
   "transAnimType": 0,
   "title": "10. Reset your password",
   "image": "10.-reset-your-password.png",
   "image2x": "10.-reset-your-password@2x.png",
   "index": 37,
   "width": 375,
   "height": 812,
   "x": 2106,
   "y": 465,
   "type": "regular",
   "fixedPanels": [],
   "links": [],
   "overlayPinPage": 6,
   "overlayOutsideClickIgnore": true,
   "layout": null
  },
  {
   "id": "59:2740",
   "groupID": "0:1",
   "transAnimType": 0,
   "title": "20. Upload - Photo ID Card & Selfie",
   "image": "20.-upload-photo-id-card-selfie.png",
   "image2x": "20.-upload-photo-id-card-selfie@2x.png",
   "index": 38,
   "width": 375,
   "height": 812,
   "x": 2106,
   "y": 1417,
   "type": "regular",
   "fixedPanels": [],
   "links": [],
   "overlayPinPage": 6,
   "overlayOutsideClickIgnore": true,
   "layout": null
  },
  {
   "id": "81:3152",
   "groupID": "0:1",
   "transAnimType": 0,
   "title": "30. Detail History",
   "image": "30.-detail-history.png",
   "image2x": "30.-detail-history@2x.png",
   "index": 39,
   "width": 375,
   "height": 812,
   "x": 2106,
   "y": 2369,
   "type": "regular",
   "fixedPanels": [],
   "links": [],
   "overlayPinPage": 6,
   "overlayOutsideClickIgnore": true,
   "layout": null
  },
  {
   "id": "87:3125",
   "groupID": "0:1",
   "transAnimType": 0,
   "title": "40. Chat Assistant",
   "image": "40.-chat-assistant.png",
   "image2x": "40.-chat-assistant@2x.png",
   "index": 40,
   "width": 375,
   "height": 812,
   "x": 2106,
   "y": 3321,
   "type": "regular",
   "fixedPanels": [],
   "links": [],
   "overlayPinPage": 6,
   "overlayOutsideClickIgnore": true,
   "layout": null
  },
  {
   "id": "47:2215",
   "groupID": "0:1",
   "transAnimType": 0,
   "title": "Label(1)",
   "image": "label(1).png",
   "image2x": "label(1)@2x.png",
   "index": 41,
   "width": 1440,
   "height": 164,
   "x": 2936,
   "y": 101,
   "type": "regular",
   "fixedPanels": [],
   "links": [],
   "overlayPinPage": 6,
   "overlayOutsideClickIgnore": true,
   "layout": null
  },
  {
   "id": "47:2227",
   "groupID": "0:1",
   "transAnimType": 0,
   "title": "1. Splash Screen - Dark",
   "image": "1.-splash-screen-dark.png",
   "image2x": "1.-splash-screen-dark@2x.png",
   "index": 42,
   "width": 375,
   "height": 812,
   "x": 2936,
   "y": 465,
   "type": "regular",
   "fixedPanels": [],
   "links": [],
   "overlayPinPage": 6,
   "overlayOutsideClickIgnore": true,
   "layout": null
  },
  {
   "id": "63:5467",
   "groupID": "0:1",
   "transAnimType": 0,
   "title": "11. Sign up - Empty - Dark",
   "image": "11.-sign-up-empty-dark.png",
   "image2x": "11.-sign-up-empty-dark@2x.png",
   "index": 43,
   "width": 375,
   "height": 812,
   "x": 2936,
   "y": 1417,
   "type": "regular",
   "fixedPanels": [],
   "links": [],
   "overlayPinPage": 6,
   "overlayOutsideClickIgnore": true,
   "layout": null
  },
  {
   "id": "65:3595",
   "groupID": "0:1",
   "transAnimType": 0,
   "title": "21. Home - Dark",
   "image": "21.-home-dark.png",
   "image2x": "21.-home-dark@2x.png",
   "index": 44,
   "width": 375,
   "height": 812,
   "x": 2936,
   "y": 2369,
   "type": "regular",
   "fixedPanels": [],
   "links": [],
   "overlayPinPage": 6,
   "overlayOutsideClickIgnore": true,
   "layout": null
  },
  {
   "id": "115:5730",
   "groupID": "0:1",
   "transAnimType": 0,
   "title": "31. Statistic - V1 - Dark",
   "image": "31.-statistic-v1-dark.png",
   "image2x": "31.-statistic-v1-dark@2x.png",
   "index": 45,
   "width": 375,
   "height": 812,
   "x": 2936,
   "y": 3321,
   "type": "regular",
   "fixedPanels": [],
   "links": [],
   "overlayPinPage": 6,
   "overlayOutsideClickIgnore": true,
   "layout": null
  },
  {
   "id": "115:4972",
   "groupID": "0:1",
   "transAnimType": 0,
   "title": "2. Onboarding - 2 - Dark",
   "image": "2.-onboarding-2-dark.png",
   "image2x": "2.-onboarding-2-dark@2x.png",
   "index": 46,
   "width": 375,
   "height": 812,
   "x": 3351,
   "y": 465,
   "type": "regular",
   "fixedPanels": [],
   "links": [],
   "overlayPinPage": 6,
   "overlayOutsideClickIgnore": true,
   "layout": null
  },
  {
   "id": "63:5488",
   "groupID": "0:1",
   "transAnimType": 0,
   "title": "12. Sign up - Filled - Dark",
   "image": "12.-sign-up-filled-dark.png",
   "image2x": "12.-sign-up-filled-dark@2x.png",
   "index": 47,
   "width": 375,
   "height": 812,
   "x": 3351,
   "y": 1417,
   "type": "regular",
   "fixedPanels": [],
   "links": [],
   "overlayPinPage": 6,
   "overlayOutsideClickIgnore": true,
   "layout": null
  },
  {
   "id": "65:3715",
   "groupID": "0:1",
   "transAnimType": 0,
   "title": "22. Topup - Dark",
   "image": "22.-topup-dark.png",
   "image2x": "22.-topup-dark@2x.png",
   "index": 48,
   "width": 375,
   "height": 812,
   "x": 3351,
   "y": 2369,
   "type": "regular",
   "fixedPanels": [],
   "links": [],
   "overlayPinPage": 6,
   "overlayOutsideClickIgnore": true,
   "layout": null
  },
  {
   "id": "115:5834",
   "groupID": "0:1",
   "transAnimType": 0,
   "title": "32. Statistic - V2 - Dark",
   "image": "32.-statistic-v2-dark.png",
   "image2x": "32.-statistic-v2-dark@2x.png",
   "index": 49,
   "width": 375,
   "height": 812,
   "x": 3351,
   "y": 3321,
   "type": "regular",
   "fixedPanels": [],
   "links": [],
   "overlayPinPage": 6,
   "overlayOutsideClickIgnore": true,
   "layout": null
  },
  {
   "id": "115:4939",
   "groupID": "0:1",
   "transAnimType": 0,
   "title": "3. Onboarding - 3 - Dark",
   "image": "3.-onboarding-3-dark.png",
   "image2x": "3.-onboarding-3-dark@2x.png",
   "index": 50,
   "width": 375,
   "height": 812,
   "x": 3766,
   "y": 465,
   "type": "regular",
   "fixedPanels": [],
   "links": [],
   "overlayPinPage": 6,
   "overlayOutsideClickIgnore": true,
   "layout": null
  },
  {
   "id": "63:5221",
   "groupID": "0:1",
   "transAnimType": 0,
   "title": "13. Country of Residence - Dark",
   "image": "13.-country-of-residence-dark.png",
   "image2x": "13.-country-of-residence-dark@2x.png",
   "index": 51,
   "width": 375,
   "height": 812,
   "x": 3766,
   "y": 1417,
   "type": "regular",
   "fixedPanels": [],
   "links": [],
   "overlayPinPage": 6,
   "overlayOutsideClickIgnore": true,
   "layout": null
  },
  {
   "id": "65:4233",
   "groupID": "0:1",
   "transAnimType": 0,
   "title": "23. Topup - Confirmation - Dark",
   "image": "23.-topup-confirmation-dark.png",
   "image2x": "23.-topup-confirmation-dark@2x.png",
   "index": 52,
   "width": 375,
   "height": 812,
   "x": 3766,
   "y": 2369,
   "type": "regular",
   "fixedPanels": [],
   "links": [],
   "overlayPinPage": 6,
   "overlayOutsideClickIgnore": true,
   "layout": null
  },
  {
   "id": "115:6644",
   "groupID": "0:1",
   "transAnimType": 0,
   "title": "33. My Card - Dark",
   "image": "33.-my-card-dark.png",
   "image2x": "33.-my-card-dark@2x.png",
   "index": 53,
   "width": 375,
   "height": 812,
   "x": 3766,
   "y": 3321,
   "type": "regular",
   "fixedPanels": [],
   "links": [],
   "overlayPinPage": 6,
   "overlayOutsideClickIgnore": true,
   "layout": null
  },
  {
   "id": "48:2382",
   "groupID": "0:1",
   "transAnimType": 0,
   "title": "4. Login - Empty - Dark",
   "image": "4.-login-empty-dark.png",
   "image2x": "4.-login-empty-dark@2x.png",
   "index": 54,
   "width": 375,
   "height": 812,
   "x": 4181,
   "y": 465,
   "type": "regular",
   "fixedPanels": [],
   "links": [],
   "overlayPinPage": 6,
   "overlayOutsideClickIgnore": true,
   "layout": null
  },
  {
   "id": "63:5232",
   "groupID": "0:1",
   "transAnimType": 0,
   "title": "14. Country of Residence - Select - Dark",
   "image": "14.-country-of-residence-select-dark.png",
   "image2x": "14.-country-of-residence-select-dark@2x.png",
   "index": 55,
   "width": 375,
   "height": 812,
   "x": 4181,
   "y": 1417,
   "type": "regular",
   "fixedPanels": [],
   "links": [],
   "overlayPinPage": 6,
   "overlayOutsideClickIgnore": true,
   "layout": null
  },
  {
   "id": "65:3844",
   "groupID": "0:1",
   "transAnimType": 0,
   "title": "24. Success - Topup - Dark",
   "image": "24.-success-topup-dark.png",
   "image2x": "24.-success-topup-dark@2x.png",
   "index": 56,
   "width": 375,
   "height": 812,
   "x": 4181,
   "y": 2369,
   "type": "regular",
   "fixedPanels": [],
   "links": [],
   "overlayPinPage": 6,
   "overlayOutsideClickIgnore": true,
   "layout": null
  },
  {
   "id": "106:3856",
   "groupID": "0:1",
   "transAnimType": 0,
   "title": "34. My Card - Add New Card - Dark",
   "image": "34.-my-card-add-new-card-dark.png",
   "image2x": "34.-my-card-add-new-card-dark@2x.png",
   "index": 57,
   "width": 375,
   "height": 812,
   "x": 4181,
   "y": 3321,
   "type": "regular",
   "fixedPanels": [],
   "links": [],
   "overlayPinPage": 6,
   "overlayOutsideClickIgnore": true,
   "layout": null
  },
  {
   "id": "48:2400",
   "groupID": "0:1",
   "transAnimType": 0,
   "title": "5. Login - Filled - Dark",
   "image": "5.-login-filled-dark.png",
   "image2x": "5.-login-filled-dark@2x.png",
   "index": 58,
   "width": 375,
   "height": 812,
   "x": 4596,
   "y": 465,
   "type": "regular",
   "fixedPanels": [],
   "links": [],
   "overlayPinPage": 6,
   "overlayOutsideClickIgnore": true,
   "layout": null
  },
  {
   "id": "63:5433",
   "groupID": "0:1",
   "transAnimType": 0,
   "title": "15. Select Reason - Dark",
   "image": "15.-select-reason-dark.png",
   "image2x": "15.-select-reason-dark@2x.png",
   "index": 59,
   "width": 375,
   "height": 812,
   "x": 4596,
   "y": 1417,
   "type": "regular",
   "fixedPanels": [],
   "links": [],
   "overlayPinPage": 6,
   "overlayOutsideClickIgnore": true,
   "layout": null
  },
  {
   "id": "88:3095",
   "groupID": "0:1",
   "transAnimType": 0,
   "title": "25. Transfer - Dark",
   "image": "25.-transfer-dark.png",
   "image2x": "25.-transfer-dark@2x.png",
   "index": 60,
   "width": 375,
   "height": 812,
   "x": 4596,
   "y": 2369,
   "type": "regular",
   "fixedPanels": [],
   "links": [],
   "overlayPinPage": 6,
   "overlayOutsideClickIgnore": true,
   "layout": null
  },
  {
   "id": "106:3966",
   "groupID": "0:1",
   "transAnimType": 0,
   "title": "35. My Card - Create Pin - Dark",
   "image": "35.-my-card-create-pin-dark.png",
   "image2x": "35.-my-card-create-pin-dark@2x.png",
   "index": 61,
   "width": 375,
   "height": 812,
   "x": 4596,
   "y": 3321,
   "type": "regular",
   "fixedPanels": [],
   "links": [],
   "overlayPinPage": 6,
   "overlayOutsideClickIgnore": true,
   "layout": null
  },
  {
   "id": "48:3038",
   "groupID": "0:1",
   "transAnimType": 0,
   "title": "6. OTP Authentication - Dark",
   "image": "6.-otp-authentication-dark.png",
   "image2x": "6.-otp-authentication-dark@2x.png",
   "index": 62,
   "width": 375,
   "height": 812,
   "x": 5011,
   "y": 465,
   "type": "regular",
   "fixedPanels": [],
   "links": [],
   "overlayPinPage": 6,
   "overlayOutsideClickIgnore": true,
   "layout": null
  },
  {
   "id": "63:5444",
   "groupID": "0:1",
   "transAnimType": 0,
   "title": "16. Create Pin - Dark",
   "image": "16.-create-pin-dark.png",
   "image2x": "16.-create-pin-dark@2x.png",
   "index": 63,
   "width": 375,
   "height": 812,
   "x": 5011,
   "y": 1417,
   "type": "regular",
   "fixedPanels": [],
   "links": [],
   "overlayPinPage": 6,
   "overlayOutsideClickIgnore": true,
   "layout": null
  },
  {
   "id": "88:3144",
   "groupID": "0:1",
   "transAnimType": 0,
   "title": "26. Transfer - Detail - Dark",
   "image": "26.-transfer-detail-dark.png",
   "image2x": "26.-transfer-detail-dark@2x.png",
   "index": 64,
   "width": 375,
   "height": 812,
   "x": 5011,
   "y": 2369,
   "type": "regular",
   "fixedPanels": [],
   "links": [],
   "overlayPinPage": 6,
   "overlayOutsideClickIgnore": true,
   "layout": null
  },
  {
   "id": "115:7118",
   "groupID": "0:1",
   "transAnimType": 0,
   "title": "36. Profile - Dark",
   "image": "36.-profile-dark.png",
   "image2x": "36.-profile-dark@2x.png",
   "index": 65,
   "width": 375,
   "height": 812,
   "x": 5011,
   "y": 3321,
   "type": "regular",
   "fixedPanels": [],
   "links": [],
   "overlayPinPage": 6,
   "overlayOutsideClickIgnore": true,
   "layout": null
  },
  {
   "id": "48:3053",
   "groupID": "0:1",
   "transAnimType": 0,
   "title": "7. Fingerprint - Dark",
   "image": "7.-fingerprint-dark.png",
   "image2x": "7.-fingerprint-dark@2x.png",
   "index": 66,
   "width": 375,
   "height": 812,
   "x": 5426,
   "y": 465,
   "type": "regular",
   "fixedPanels": [],
   "links": [],
   "overlayPinPage": 6,
   "overlayOutsideClickIgnore": true,
   "layout": null
  },
  {
   "id": "63:5456",
   "groupID": "0:1",
   "transAnimType": 0,
   "title": "17. Verify Identity - Dark",
   "image": "17.-verify-identity-dark.png",
   "image2x": "17.-verify-identity-dark@2x.png",
   "index": 67,
   "width": 375,
   "height": 812,
   "x": 5426,
   "y": 1417,
   "type": "regular",
   "fixedPanels": [],
   "links": [],
   "overlayPinPage": 6,
   "overlayOutsideClickIgnore": true,
   "layout": null
  },
  {
   "id": "88:3823",
   "groupID": "0:1",
   "transAnimType": 0,
   "title": "27. Transfer - Confirm - Dark",
   "image": "27.-transfer-confirm-dark.png",
   "image2x": "27.-transfer-confirm-dark@2x.png",
   "index": 68,
   "width": 375,
   "height": 812,
   "x": 5426,
   "y": 2369,
   "type": "regular",
   "fixedPanels": [],
   "links": [],
   "overlayPinPage": 6,
   "overlayOutsideClickIgnore": true,
   "layout": null
  },
  {
   "id": "115:7334",
   "groupID": "0:1",
   "transAnimType": 0,
   "title": "37. My Account - Dark",
   "image": "37.-my-account-dark.png",
   "image2x": "37.-my-account-dark@2x.png",
   "index": 69,
   "width": 375,
   "height": 812,
   "x": 5426,
   "y": 3321,
   "type": "regular",
   "fixedPanels": [],
   "links": [],
   "overlayPinPage": 6,
   "overlayOutsideClickIgnore": true,
   "layout": null
  },
  {
   "id": "48:3079",
   "groupID": "0:1",
   "transAnimType": 0,
   "title": "8. Password Recovery - Dark",
   "image": "8.-password-recovery-dark.png",
   "image2x": "8.-password-recovery-dark@2x.png",
   "index": 70,
   "width": 375,
   "height": 812,
   "x": 5841,
   "y": 465,
   "type": "regular",
   "fixedPanels": [],
   "links": [],
   "overlayPinPage": 6,
   "overlayOutsideClickIgnore": true,
   "layout": null
  },
  {
   "id": "63:5509",
   "groupID": "0:1",
   "transAnimType": 0,
   "title": "18. Proof of residency  - Dark",
   "image": "18.-proof-of-residency-dark.png",
   "image2x": "18.-proof-of-residency-dark@2x.png",
   "index": 71,
   "width": 375,
   "height": 812,
   "x": 5841,
   "y": 1417,
   "type": "regular",
   "fixedPanels": [],
   "links": [],
   "overlayPinPage": 6,
   "overlayOutsideClickIgnore": true,
   "layout": null
  },
  {
   "id": "88:3238",
   "groupID": "0:1",
   "transAnimType": 0,
   "title": "28. Transfer - Proof - Dark",
   "image": "28.-transfer-proof-dark.png",
   "image2x": "28.-transfer-proof-dark@2x.png",
   "index": 72,
   "width": 375,
   "height": 812,
   "x": 5841,
   "y": 2369,
   "type": "regular",
   "fixedPanels": [],
   "links": [],
   "overlayPinPage": 6,
   "overlayOutsideClickIgnore": true,
   "layout": null
  },
  {
   "id": "106:3591",
   "groupID": "0:1",
   "transAnimType": 0,
   "title": "38. Settings - Dark",
   "image": "38.-settings-dark.png",
   "image2x": "38.-settings-dark@2x.png",
   "index": 73,
   "width": 375,
   "height": 812,
   "x": 5841,
   "y": 3321,
   "type": "regular",
   "fixedPanels": [],
   "links": [],
   "overlayPinPage": 6,
   "overlayOutsideClickIgnore": true,
   "layout": null
  },
  {
   "id": "48:3090",
   "groupID": "0:1",
   "transAnimType": 0,
   "title": "9. Verify your identity - Dark",
   "image": "9.-verify-your-identity-dark.png",
   "image2x": "9.-verify-your-identity-dark@2x.png",
   "index": 74,
   "width": 375,
   "height": 812,
   "x": 6256,
   "y": 465,
   "type": "regular",
   "fixedPanels": [],
   "links": [],
   "overlayPinPage": 6,
   "overlayOutsideClickIgnore": true,
   "layout": null
  },
  {
   "id": "63:5557",
   "groupID": "0:1",
   "transAnimType": 0,
   "title": "19. Upload - Photo ID Card - Dark",
   "image": "19.-upload-photo-id-card-dark.png",
   "image2x": "19.-upload-photo-id-card-dark@2x.png",
   "index": 75,
   "width": 375,
   "height": 812,
   "x": 6256,
   "y": 1417,
   "type": "regular",
   "fixedPanels": [],
   "links": [],
   "overlayPinPage": 6,
   "overlayOutsideClickIgnore": true,
   "layout": null
  },
  {
   "id": "88:3285",
   "groupID": "0:1",
   "transAnimType": 0,
   "title": "29. History Trasaction - Dark",
   "image": "29.-history-trasaction-dark.png",
   "image2x": "29.-history-trasaction-dark@2x.png",
   "index": 76,
   "width": 375,
   "height": 812,
   "x": 6256,
   "y": 2369,
   "type": "regular",
   "fixedPanels": [],
   "links": [],
   "overlayPinPage": 6,
   "overlayOutsideClickIgnore": true,
   "layout": null
  },
  {
   "id": "115:7673",
   "groupID": "0:1",
   "transAnimType": 0,
   "title": "39. Notification - Dark",
   "image": "39.-notification-dark.png",
   "image2x": "39.-notification-dark@2x.png",
   "index": 77,
   "width": 375,
   "height": 812,
   "x": 6256,
   "y": 3321,
   "type": "regular",
   "fixedPanels": [],
   "links": [],
   "overlayPinPage": 6,
   "overlayOutsideClickIgnore": true,
   "layout": null
  },
  {
   "id": "48:3105",
   "groupID": "0:1",
   "transAnimType": 0,
   "title": "10. Reset your password - Dark",
   "image": "10.-reset-your-password-dark.png",
   "image2x": "10.-reset-your-password-dark@2x.png",
   "index": 78,
   "width": 375,
   "height": 812,
   "x": 6671,
   "y": 465,
   "type": "regular",
   "fixedPanels": [],
   "links": [],
   "overlayPinPage": 6,
   "overlayOutsideClickIgnore": true,
   "layout": null
  },
  {
   "id": "63:5543",
   "groupID": "0:1",
   "transAnimType": 0,
   "title": "20. Upload - Photo ID Card & Selfie - Dark",
   "image": "20.-upload-photo-id-card-selfie-dark.png",
   "image2x": "20.-upload-photo-id-card-selfie-dark@2x.png",
   "index": 79,
   "width": 375,
   "height": 812,
   "x": 6671,
   "y": 1417,
   "type": "regular",
   "fixedPanels": [],
   "links": [],
   "overlayPinPage": 6,
   "overlayOutsideClickIgnore": true,
   "layout": null
  },
  {
   "id": "88:3466",
   "groupID": "0:1",
   "transAnimType": 0,
   "title": "30. Detail History - Dark",
   "image": "30.-detail-history-dark.png",
   "image2x": "30.-detail-history-dark@2x.png",
   "index": 80,
   "width": 375,
   "height": 812,
   "x": 6671,
   "y": 2369,
   "type": "regular",
   "fixedPanels": [],
   "links": [],
   "overlayPinPage": 6,
   "overlayOutsideClickIgnore": true,
   "layout": null
  },
  {
   "id": "106:3560",
   "groupID": "0:1",
   "transAnimType": 0,
   "title": "40. Chat Assistant - Dark",
   "image": "40.-chat-assistant-dark.png",
   "image2x": "40.-chat-assistant-dark@2x.png",
   "index": 81,
   "width": 375,
   "height": 812,
   "x": 6671,
   "y": 3321,
   "type": "regular",
   "fixedPanels": [],
   "links": [],
   "overlayPinPage": 6,
   "overlayOutsideClickIgnore": true,
   "layout": null
  },
  {
   "id": "106:4206",
   "groupID": "2:3",
   "transAnimType": 0,
   "title": "Cover",
   "image": "cover.png",
   "image2x": "cover@2x.png",
   "index": 82,
   "width": 596,
   "height": 320,
   "x": -2336,
   "y": -1327,
   "type": "regular",
   "fixedPanels": [],
   "links": [],
   "overlayPinPage": 6,
   "overlayOutsideClickIgnore": true,
   "layout": null
  },
  {
   "id": "10:2413",
   "groupID": "2:3",
   "transAnimType": 0,
   "title": "Typography",
   "image": "typography.png",
   "image2x": "typography@2x.png",
   "index": 83,
   "width": 1440,
   "height": 1678,
   "x": -1580,
   "y": -1327,
   "type": "regular",
   "fixedPanels": [],
   "links": [],
   "overlayPinPage": 6,
   "overlayOutsideClickIgnore": true,
   "layout": null
  },
  {
   "id": "10:2662",
   "groupID": "2:3",
   "transAnimType": 0,
   "title": "Color Palette",
   "image": "color-palette.png",
   "image2x": "color-palette@2x.png",
   "index": 84,
   "width": 1440,
   "height": 1428,
   "x": 20,
   "y": -1327,
   "type": "regular",
   "fixedPanels": [],
   "links": [],
   "overlayPinPage": 6,
   "overlayOutsideClickIgnore": true,
   "layout": null
  },
  {
   "id": "7:534",
   "groupID": "2:2",
   "transAnimType": 0,
   "title": "Icons",
   "image": "icons.png",
   "image2x": "icons@2x.png",
   "index": 85,
   "width": 1440,
   "height": 749,
   "x": -720,
   "y": -2109,
   "type": "regular",
   "fixedPanels": [],
   "links": [],
   "overlayPinPage": 6,
   "overlayOutsideClickIgnore": true,
   "layout": null
  },
  {
   "id": "7:2077",
   "groupID": "2:2",
   "transAnimType": 0,
   "title": "Components",
   "image": "components.png",
   "image2x": "components@2x.png",
   "index": 86,
   "width": 1440,
   "height": 7166,
   "x": 880,
   "y": -2109,
   "type": "regular",
   "fixedPanels": [],
   "links": [],
   "overlayPinPage": 6,
   "overlayOutsideClickIgnore": true,
   "layout": null
  }
 ],
 "groups": [
  {
   "id": "0:1",
   "name": "Visual Design"
  },
  {
   "id": "2:3",
   "name": "Styleguide"
  },
  {
   "id": "2:2",
   "name": "Components"
  }
 ],
 "startPageIndex": 0,
 "totalImages": 87,
 "backColor": "#B9BBB6"
}